{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Using pad_token, but it is not set yet.\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\callbacks\\manager.py\", line 2072, in _configure\n",
      "    handler = LangChainTracer(project_name=tracer_project)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\callbacks\\tracers\\langchain.py\", line 97, in __init__\n",
      "    self.client = client or get_client()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\callbacks\\tracers\\langchain.py\", line 55, in get_client\n",
      "    _CLIENT = Client()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langsmith\\client.py\", line 272, in __init__\n",
      "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langsmith\\client.py\", line 181, in _validate_api_key_if_hosted\n",
      "    raise ls_utils.LangSmithUserError(\n",
      "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1098, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 942, in format\n",
      "    return fmt.format(record)\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 678, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 368, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1046, in launch_instance\n",
      "    app.start()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 736, in start\n",
      "    self.io_loop.start()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 595, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 1881, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 516, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 505, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 412, in dispatch_shell\n",
      "    await result\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 740, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 546, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3024, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3079, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3284, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3466, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3526, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Temp\\ipykernel_9044\\3671982202.py\", line 17, in <module>\n",
      "    chain.invoke({\"word\": \"Chocolate Pie\"})\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\schema\\runnable\\base.py\", line 1204, in invoke\n",
      "    callback_manager = get_callback_manager_for_config(config)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\schema\\runnable\\config.py\", line 363, in get_callback_manager_for_config\n",
      "    return CallbackManager.configure(\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\callbacks\\manager.py\", line 1479, in configure\n",
      "    return _configure(\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\callbacks\\manager.py\", line 2075, in _configure\n",
      "    logger.warning(\n",
      "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the  LANGCHAIN_TRACING_V2 environment variables.'\n",
      "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\callbacks\\manager.py\", line 2072, in _configure\n",
      "    handler = LangChainTracer(project_name=tracer_project)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\callbacks\\tracers\\langchain.py\", line 97, in __init__\n",
      "    self.client = client or get_client()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\callbacks\\tracers\\langchain.py\", line 55, in get_client\n",
      "    _CLIENT = Client()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langsmith\\client.py\", line 272, in __init__\n",
      "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langsmith\\client.py\", line 181, in _validate_api_key_if_hosted\n",
      "    raise ls_utils.LangSmithUserError(\n",
      "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1098, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 942, in format\n",
      "    return fmt.format(record)\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 678, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 368, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1046, in launch_instance\n",
      "    app.start()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 736, in start\n",
      "    self.io_loop.start()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 595, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 1881, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 516, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 505, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 412, in dispatch_shell\n",
      "    await result\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 740, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 546, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3024, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3079, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3284, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3466, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3526, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Temp\\ipykernel_9044\\3671982202.py\", line 17, in <module>\n",
      "    chain.invoke({\"word\": \"Chocolate Pie\"})\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\schema\\runnable\\base.py\", line 1213, in invoke\n",
      "    input = step.invoke(\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\schema\\prompt_template.py\", line 60, in invoke\n",
      "    return self._call_with_config(\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\schema\\runnable\\base.py\", line 707, in _call_with_config\n",
      "    callback_manager = get_callback_manager_for_config(config)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\schema\\runnable\\config.py\", line 363, in get_callback_manager_for_config\n",
      "    return CallbackManager.configure(\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\callbacks\\manager.py\", line 1479, in configure\n",
      "    return _configure(\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\callbacks\\manager.py\", line 2075, in _configure\n",
      "    logger.warning(\n",
      "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the  LANGCHAIN_TRACING_V2 environment variables.'\n",
      "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\callbacks\\manager.py\", line 2072, in _configure\n",
      "    handler = LangChainTracer(project_name=tracer_project)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\callbacks\\tracers\\langchain.py\", line 97, in __init__\n",
      "    self.client = client or get_client()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\callbacks\\tracers\\langchain.py\", line 55, in get_client\n",
      "    _CLIENT = Client()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langsmith\\client.py\", line 272, in __init__\n",
      "    _validate_api_key_if_hosted(self.api_url, self.api_key)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langsmith\\client.py\", line 181, in _validate_api_key_if_hosted\n",
      "    raise ls_utils.LangSmithUserError(\n",
      "langsmith.utils.LangSmithUserError: API key must be provided when using hosted LangSmith API\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1098, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 942, in format\n",
      "    return fmt.format(record)\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 678, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 368, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\traitlets\\config\\application.py\", line 1046, in launch_instance\n",
      "    app.start()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 736, in start\n",
      "    self.io_loop.start()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 195, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 595, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 1881, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 516, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 505, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 412, in dispatch_shell\n",
      "    await result\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 740, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 422, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 546, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3024, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3079, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3284, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3466, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3526, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\first\\AppData\\Local\\Temp\\ipykernel_9044\\3671982202.py\", line 17, in <module>\n",
      "    chain.invoke({\"word\": \"Chocolate Pie\"})\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\schema\\runnable\\base.py\", line 1213, in invoke\n",
      "    input = step.invoke(\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\llms\\base.py\", line 229, in invoke\n",
      "    self.generate_prompt(\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\llms\\base.py\", line 507, in generate_prompt\n",
      "    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\llms\\base.py\", line 614, in generate\n",
      "    CallbackManager.configure(\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\callbacks\\manager.py\", line 1479, in configure\n",
      "    return _configure(\n",
      "  File \"d:\\Project\\SangmooGPT\\env\\lib\\site-packages\\langchain\\callbacks\\manager.py\", line 2075, in _configure\n",
      "    logger.warning(\n",
      "Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the  LANGCHAIN_TRACING_V2 environment variables.'\n",
      "Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith API'),)\n",
      "Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "\" very old dessert, because it's hard to explain. We just use old chocolate to make it to be chocolate pie again, but you need a very special kind of chocolate to do this.\\n\\nBakaloo, which is so popular in our village, is a traditional holiday for many who live in North London. Even though we have some shops offering their own bakery on the outskirts of London this year, there is always something to be said about their bakery, which means that we have to be careful about our dessert choices. The bakery will usually take us into an exclusive kitchen with no windows because most of the food is served within ten metres away. However, the shop has the option of opening on Sundays where the baking is done by special\""
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from langchain.llms.huggingface_pipeline import HuggingFacePipeline\n",
    "from langchain.prompts import PromptTemplate\n",
    "\n",
    "prompt = PromptTemplate.from_template(\"A {word} is a\")\n",
    "\n",
    "# If the model is not available, proceed with the download\n",
    "llm = HuggingFacePipeline.from_model_id(\n",
    "    model_id=\"gpt2\",\n",
    "    # model_id=\"tiiuae/falcon-7b-instruct\",\n",
    "    task=\"text-generation\",\n",
    "    # device=0, # 0 == GPU , -1 == CPU , IF 0 is not available on MacBook\n",
    "    pipeline_kwargs={\"max_new_tokens\": 150},\n",
    ")\n",
    "\n",
    "chain = prompt | llm\n",
    "\n",
    "chain.invoke({\"word\": \"Chocolate Pie\"})"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
